app:
  name: "Mazharul-Islam Service"
  slug_name: "mazharul-islam-service"
  version: "1.0.0"
build: 1
mode: "dev"
port: "4000"
db:
  host: "localhost"
  port: "5432"
  name: "mazharul-islam"
  user: "septian"
  password: "secret"
  ssl_mode: "disable"
  timezone: "Asia/Jakarta"
  max_idle_conns: 2
  max_open_conns: 5
  conn_max_lifetime: "1h"
  ping_interval: "5000ms"
  retry_attempts: 3
redis:
  dial_timeout: 5
  write_timeout: 2
  read_timeout: 2
  max_idle_conn: 20
  max_active_conn: 50
  cache_host: "redis://localhost:6379/7"
log_level: "debug"
enable_caching: true
cache_ttl: "15m"
swagger:
  username: "swagger"
  password: "secret"
basic:
  auth:
    username: configure-by-env
    password: configure-by-env  
